In [4]:
import numpy as np


In [6]:
a = np.array([1,2,3], dtype ='int16')
print(a)

[1 2 3]


In [7]:
b = np.array([[5.0,6.0,7.0,7.5],[8.0,9.0,10.0,11.0]])
print (b)

[[ 5.  6.  7.]
 [ 8.  9. 10.]]


In [8]:
# get the dimension
a.ndim

1

In [9]:
b.ndim

2

In [12]:
# get the shape
a.shape


(3,)

In [13]:
 b.shape

(2, 3)

In [22]:
# get type 
a.dtype

dtype('int64')

In [23]:
# get size
a.itemsize

8

In [27]:
# get total size
a.size
a.size*a.itemsize
a.nbytes

24

In [28]:
# floats bigger than integer
b.itemsize

8

In [32]:
# get specific element[r,c]
b[1,0]

8.0

In [33]:
# get a specific row
b[0,:]

array([5., 6., 7.])

In [34]:
# get a specific column
b[:,2]


array([ 7., 10.])

In [40]:
# [startindex,stepindex,stepssize]
b[1,0:-1:2]

array([8.])

In [42]:
# update 
b[1,-1] = 20.0
print(b)

# for column
b[:,2]= 10.0
print(b)

[[ 5.  6.  7.]
 [ 8.  9. 20.]]
[[ 5.  6. 10.]
 [ 8.  9. 10.]]


In [44]:
# 3d example
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
# get specific elemnt (outside in)
c[0,1,0]
c[:,1,:]

array([[3, 4],
       [7, 8]])

In [52]:
# Replace
c[:,1,:] = [[9,9],[8,8]]
print(c)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [67]:
# all 0 matrix
np.zeros(5)
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [68]:
# All 1s in matrix
np.ones((4,2,2),dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [71]:
# any other number np.full(shape,value)
np.full((2,2),99, dtype='float32')


array([[99., 99.],
       [99., 99.]], dtype=float32)

In [74]:
# any other (full_live)
np.full_like(c,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [75]:
np.full(c.shape,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [78]:
# random decimal numbers
np.random.rand(4,2)
np.random.rand(4,2,3)

array([[[0.97413732, 0.45287176, 0.02741927],
        [0.28467517, 0.20043997, 0.32872631]],

       [[0.10825524, 0.1946981 , 0.56975177],
        [0.98438782, 0.60025864, 0.91282937]],

       [[0.14201725, 0.39262016, 0.99674341],
        [0.51975033, 0.68219482, 0.76932183]],

       [[0.27369138, 0.90924164, 0.3268639 ],
        [0.55518195, 0.22963589, 0.77975747]]])

In [79]:
np.random.random_sample(c.shape)

array([[[0.28043594, 0.77230975],
        [0.41141195, 0.07185079]],

       [[0.42650945, 0.25230791],
        [0.28477344, 0.92429784]]])

In [88]:
# Random integer value
np.random.randint(-2,10,size=(3,3))

array([[ 3,  4,  9],
       [ 0,  3,  7],
       [ 6,  9, -1]])

In [89]:
# The identity  matrix square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [95]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5,axis=1)
print(r1)

[[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]]


In [99]:
output = np.ones((5,5))
print (output)

z = np.zeros((3,3))
z[1,1] = 9
print (z)
# first row to the 4th row
output[1:4,1:4] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [104]:
output = np.zeros((7,7))
print (output)

z = np.ones((5,5))
z[2,2]=5
print(z)

output[1:-1,1:-1] = z
print (output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [105]:
# BE careful when copying arrays

a = np.array ([1,2,3])
b = a
b[0] = 100
# changes a too 
print(b)
print(a)

[100   2   3]


In [107]:
a = np.array ([1,2,3])
b = a.copy()
b[0]=100
print (b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics

In [130]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [131]:
a + 2

array([3, 4, 5, 6])

In [132]:
a - 1

array([0, 1, 2, 3])

In [118]:
a * 2

array([2, 4, 6, 8])

In [119]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [133]:
b = np.array([1,0,1,0])
a + b


array([2, 2, 4, 4])

In [134]:
a ** 2

array([ 1,  4,  9, 16])

In [135]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear algerbera

In [138]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [139]:
# find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

# statics

In [141]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
np.max(stats, axis = 1)

array([3, 6])

In [145]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [149]:
np.sum(stats, axis = 0)

array([ 6, 15])

In [ ]:
# Reorganizing Arrays

In [158]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print (before)

after = before.reshape((2,2,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [161]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [162]:
# Horizontanal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [164]:
# load data from files
filedata = np.genfromtxt('data.txt',delimeter = ',')
# copy that data from 

filedata = filedata.astype('int32')
filedata

Boolean Masking and Advanced indexing 

In [ ]:
filedata > 50

In [ ]:
filedata[filedata > 50]

In [ ]:
# you can index with a list in a NumPY
a = np.array ([1,2,3,4,5,6,7,8,9])
a[1,4,8]

In [ ]:
np.any(filedata > 50, axis = 0)

In [ ]:
# for rows
np.all(filedata > 50, axis = 1)

((filedata > 50) & (filedata < 100))

# ~ not greater than  
((filedata > 50) & (filedata < 100))

In [ ]:
a[2:4,0:2]

In [ ]:
a[[0,1,2,3], [1,2,3,4]]

In [ ]:
a[[0,-2,-1],[-2,-1]]
a[[0,4,5], 3:]